### ISSUE TITLE
Error: No element found for selector: #mat-input-0

### ISSUE THREAD

**Issue by 3guboff** [nickovchinnikov/inpol.mazowieckie_appointment_pl#1]
Hi @nickovchinnikov. When I'm trying to run `npm start` the browser opens fine, but it doesn't see `#mat-input-0` selector. I've checked on site and the selector is correct. Can you help me?

```
➜  inpol.mazowieckie_appointment_pl git:(master) ✗ npm start

> urzand@1.0.0 start
> node ./script.js

Error:  Error: No element found for selector: #mat-input-0
    at assert (file:///home/sasha/git/my/bots/inpol.mazowieckie_appointment_pl/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:25:15)
    at IsolatedWorld.type (file:///home/sasha/git/my/bots/inpol.mazowieckie_appointment_pl/node_modules/puppeteer-core/lib/esm/puppeteer/common/IsolatedWorld.js:262:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async auth (file:///home/sasha/git/my/bots/inpol.mazowieckie_appointment_pl/script.js:7:3)
    at async runner (file:///home/sasha/git/my/bots/inpol.mazowieckie_appointment_pl/script.js:76:5)
No Dates!
```
![image](https://github.com/nickovchinnikov/inpol.mazowieckie_appointment_pl/assets/1561986/caf49826-1676-48ee-84a0-c6f1181d1695)

**Comment by nickovchinnikov** [comment]
This script was released before the Google captcha. Now it's not working, sorry for this!
